/******************************************************************************
 * Copyright (C) 2014-2021 Infineon Technologies AG
 * All rights reserved.
 ******************************************************************************
 * This software contains proprietary information of Infineon Technologies AG.
 * Passing on and copying of this software, and communication of its contents
 * is not permitted without Infineon's prior written authorisation.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/

#ifndef BGT60_REGS_H_
#define BGT60_REGS_H_

#define BGT60_REG_MAIN             (0x00UL)
#define BGT60_REG_ADC0             (0x01UL)
#define BGT60_REG_CHIP_ID          (0x02UL)
#define BGT60_REG_STAT1            (0x03UL)
#define BGT60_REG_PACR1            (0x04UL)
#define BGT60_REG_PACR2            (0x05UL)
#define BGT60_REG_SFCTL            (0x06UL)
#define BGT60_REG_SADC_CTRL        (0x07UL)
#define BGT60_REG_CSI_0            (0x08UL)
#define BGT60_REG_CSI_1            (0x09UL)
#define BGT60_REG_CSI_2            (0x0aUL)
#define BGT60_REG_CSCI             (0x0bUL)
#define BGT60_REG_CSDS_0           (0x0cUL)
#define BGT60_REG_CSDS_1           (0x0dUL)
#define BGT60_REG_CSDS_2           (0x0eUL)
#define BGT60_REG_CSCDS            (0x0fUL)
#define BGT60_REG_CS1_U_0          (0x10UL)
#define BGT60_REG_CS1_U_1          (0x11UL)
#define BGT60_REG_CS1_U_2          (0x12UL)
#define BGT60_REG_CS1_D_0          (0x13UL)
#define BGT60_REG_CS1_D_1          (0x14UL)
#define BGT60_REG_CS1_D_2          (0x15UL)
#define BGT60_REG_CSC1             (0x16UL)
#define BGT60_REG_CS2_U_0          (0x17UL)
#define BGT60_REG_CS2_U_1          (0x18UL)
#define BGT60_REG_CS2_U_2          (0x19UL)
#define BGT60_REG_CS2_D_0          (0x1aUL)
#define BGT60_REG_CS2_D_1          (0x1bUL)
#define BGT60_REG_CS2_D_2          (0x1cUL)
#define BGT60_REG_CSC2             (0x1dUL)
#define BGT60_REG_CS3_U_0          (0x1eUL)
#define BGT60_REG_CS3_U_1          (0x1fUL)
#define BGT60_REG_CS3_U_2          (0x20UL)
#define BGT60_REG_CS3_D_0          (0x21UL)
#define BGT60_REG_CS3_D_1          (0x22UL)
#define BGT60_REG_CS3_D_2          (0x23UL)
#define BGT60_REG_CSC3             (0x24UL)
#define BGT60_REG_CS4_U_0          (0x25UL)
#define BGT60_REG_CS4_U_1          (0x26UL)
#define BGT60_REG_CS4_U_2          (0x27UL)
#define BGT60_REG_CS4_D_0          (0x28UL)
#define BGT60_REG_CS4_D_1          (0x29UL)
#define BGT60_REG_CS4_D_2          (0x2aUL)
#define BGT60_REG_CSC4             (0x2bUL)
#define BGT60_REG_CCR0             (0x2cUL)
#define BGT60_REG_CCR1             (0x2dUL)
#define BGT60_REG_CCR2             (0x2eUL)
#define BGT60_REG_CCR3             (0x2fUL)
#define BGT60_REG_PLL1_0           (0x30UL)
#define BGT60_REG_PLL1_1           (0x31UL)
#define BGT60_REG_PLL1_2           (0x32UL)
#define BGT60_REG_PLL1_3           (0x33UL)
#define BGT60_REG_PLL1_4           (0x34UL)
#define BGT60_REG_PLL1_5           (0x35UL)
#define BGT60_REG_PLL1_6           (0x36UL)
#define BGT60_REG_PLL1_7           (0x37UL)
#define BGT60_REG_PLL2_0           (0x38UL)
#define BGT60_REG_PLL2_1           (0x39UL)
#define BGT60_REG_PLL2_2           (0x3aUL)
#define BGT60_REG_PLL2_3           (0x3bUL)
#define BGT60_REG_PLL2_4           (0x3cUL)
#define BGT60_REG_PLL2_5           (0x3dUL)
#define BGT60_REG_PLL2_6           (0x3eUL)
#define BGT60_REG_PLL2_7           (0x3fUL)
#define BGT60_REG_PLL3_0           (0x40UL)
#define BGT60_REG_PLL3_1           (0x41UL)
#define BGT60_REG_PLL3_2           (0x42UL)
#define BGT60_REG_PLL3_3           (0x43UL)
#define BGT60_REG_PLL3_4           (0x44UL)
#define BGT60_REG_PLL3_5           (0x45UL)
#define BGT60_REG_PLL3_6           (0x46UL)
#define BGT60_REG_PLL3_7           (0x47UL)
#define BGT60_REG_PLL4_0           (0x48UL)
#define BGT60_REG_PLL4_1           (0x49UL)
#define BGT60_REG_PLL4_2           (0x4aUL)
#define BGT60_REG_PLL4_3           (0x4bUL)
#define BGT60_REG_PLL4_4           (0x4cUL)
#define BGT60_REG_PLL4_5           (0x4dUL)
#define BGT60_REG_PLL4_6           (0x4eUL)
#define BGT60_REG_PLL4_7           (0x4fUL)
#define BGT60_REG_ADC1             (0x50UL)
#define BGT60_REG_ADC2             (0x51UL)
#define BGT60_REG_ADC3             (0x52UL)
#define BGT60_REG_ADC4             (0x53UL)
#define BGT60_REG_ADC5             (0x54UL)
#define BGT60_REG_RFT0             (0x55UL)
#define BGT60_REG_RFT1             (0x56UL)
#define BGT60_REG_DFT0             (0x57UL)
#define BGT60_REG_DFT1             (0x58UL)
#define BGT60_REG_PDFT0            (0x59UL)
#define BGT60_REG_PDFT1            (0x5aUL)
#define BGT60_REG_SDFT0            (0x5bUL)
#define BGT60_REG_SDFT1            (0x5cUL)
#define BGT60_REG_STAT0            (0x5dUL)
#define BGT60_REG_SADC_RESULT      (0x5eUL)
#define BGT60_REG_FSTAT            (0x5fUL)

/* MAIN Register Definitions */
#define BGT60_REG_MAIN_FRAME_START_POS      (0UL)
#define BGT60_REG_MAIN_FRAME_START_MSK      (1UL << BGT60_REG_MAIN_FRAME_START_POS)
#define BGT60_REG_MAIN_SW_RESET_POS         (1UL)
#define BGT60_REG_MAIN_SW_RESET_MSK         (1UL << BGT60_REG_MAIN_SW_RESET_POS)
#define BGT60_REG_MAIN_FSM_RESET_POS        (2UL)
#define BGT60_REG_MAIN_FSM_RESET_MSK        (1UL << BGT60_REG_MAIN_FSM_RESET_POS)
#define BGT60_REG_MAIN_FIFO_RESET_POS       (3UL)
#define BGT60_REG_MAIN_FIFO_RESET_MSK       (1UL << BGT60_REG_MAIN_FIFO_RESET_POS)
#define BGT60_MAIN_TWKUP_POS                (4UL)
#define BGT60_MAIN_TWKUP_MSK                (0xff << BGT60_MAIN_TWKUP_POS)
#define BGT60_MAIN_TWKUP_MUL_POS            (12UL)
#define BGT60_MAIN_TWKUP_MUL_MSK            (0xf << BGT60_MAIN_TWKUP_MUL_POS)
#define BGT60_MAIN_CW_MODE_POS              (16UL)
#define BGT60_MAIN_CW_MODE_MSK              (1UL << BGT60_MAIN_CW_MODE_POS)
#define BGT60_MAIN_SADC_CLK_DIV_POS         (17UL)
#define BGT60_MAIN_SADC_CLK_DIV_MSK         (0x3 << BGT60_MAIN_SADC_CLK_DIV_POS)
#define BGT60_MAIN_BG_CLK_DIV_POS           (19UL)
#define BGT60_MAIN_BG_CLK_DIV_MSK           (0x3 << BGT60_MAIN_BG_CLK_DIV_POS)
#define BGT60_MAIN_LOAD_STRENGTH_POS        (21UL)
#define BGT60_MAIN_LOAD_STRENGTH_MSK        (0x3 << BGT60_MAIN_LOAD_STRENGTH_POS)
#define BGT60_MAIN_LDO_MODE_POS             (23UL)
#define BGT60_MAIN_LDO_MODE_MSK             (1UL << BGT60_MAIN_LDO_MODE_POS)

/* ADC0 Register Definitions */
#define BGT60_ADC0_ADC_OVERS_CFG_POS        (0UL)
#define BGT60_ADC0_ADC_OVERS_CFG_MSK        (0x3 << BGT60_ADC0_ADC_OVERS_CFG_POS)
#define BGT60_ADC0_BG_TC_TRIM_POS           (2UL)
#define BGT60_ADC0_BG_TC_TRIM_MSK           (0x7 << BGT60_ADC0_BG_TC_TRIM_POS)
#define BGT60_ADC0_BG_CHOP_EN_POS           (5UL)
#define BGT60_ADC0_BG_CHOP_EN_MSK           (0x1 << BGT60_ADC0_BG_CHOP_EN_POS)
#define BGT60_ADC0_STC_POS                  (6UL)
#define BGT60_ADC0_STC_MSK                  (0x3 << BGT60_ADC0_STC_POS)
#define BGT60_ADC0_DSCAL_POS                (8UL)
#define BGT60_ADC0_DSCAL_MSK                (0x1 << BGT60_ADC0_DSCAL_POS)
#define BGT60_ADC0_TRACK_CFG_POS            (9UL)
#define BGT60_ADC0_TRACK_CFG_MSK            (0x3 << BGT60_ADC0_TRACK_CFG_POS)
#define BGT60_ADC0_MSB_CTRL_POS             (11UL)
#define BGT60_ADC0_MSB_CTRL_MSK             (0x1 << BGT60_ADC0_MSB_CTRL_POS)
#define BGT60_ADC0_TRIG_MADC_POS            (12UL)
#define BGT60_ADC0_TRIG_MADC_MSK            (0x1 << BGT60_ADC0_TRIG_MADC_POS)
#define BGT60_ADC0_ADC_DIV_POS              (14UL)
#define BGT60_ADC0_ADC_DIV_MSK              (0x3ff << BGT60_ADC0_ADC_DIV_POS)

/* CHIP_ID Register Definitions */
#define BGT60_CHIP_ID_RF_ID_POS             (0UL)
#define BGT60_CHIP_ID_RF_ID_MSK             (0xff << BGT60_CHIP_ID_RF_ID_POS)
#define BGT60_CHIP_ID_DIGITAL_ID_POS        (8UL)
#define BGT60_CHIP_ID_DIGITAL_ID_MSK        (0xffff << BGT60_CHIP_ID_DIGITAL_ID_POS)

#define BGT60_REG_SFCTL_FIFO_CREF_POS   (0UL)
#define BGT60_REG_SFCTL_FIFO_CREF_MSK   (0x1FFFUL << BGT60_REG_SFCTL_FIFO_CREF_POS)
#define BGT60_REG_SFCTL_LFSR_EN_POS     (17UL)
#define BGT60_REG_SFCTL_LFSR_EN_MSK     (1UL << BGT60_REG_SFCTL_LFSR_EN_POS)

#endif